```{r load packages, echo=F, message=F, warning=F} library(tidyverse) library(readxl) library(reactable) library(leaflet) library(htmltools) ``` ```{r load data, echo=F, message=F, warning=F} chapters <- read_excel("bugbook_data.xlsx", sheet = "chapters") authors <- read_excel("bugbook_data.xlsx", sheet = "authors") ``` <body> <p style="text-align: justify;"> The BugBook project was initiated and coordinated by David Deruytter (Inagro, Belgium), and brings together expertise from across Europe and beyond to address the growing need for standardized research in the field of industrial insect rearing. Comprising 13 chapters (Table 1), the BugBook project provides a comprehensive and accessible manual for researchers and professionals working on the production of insects for food and feed, with a particular focus on harmonizing methodologies and experimental design. </p> <figcaption> <b>Table 1. Overview of the 13 BugBook chapters.</b> Click on the arrows on the right side to expand the abstract and further information. </figcaption> ```{r chapters, echo=F, message=F, warning=F} reactable(chapters, columns = list( Chapter = colDef(name = "#", maxWidth = 40, align = "center"), First_Author = colDef(name = "First author", minWidth = 130), Title = colDef(name = "Title", html = TRUE, minWidth = 500), Authors = colDef(show = FALSE), Abstract = colDef(show = FALSE), Keywords = colDef(show = FALSE), DOI = colDef(name = "DOI", minWidth = 50, html = TRUE, cell = function(value) { sprintf('<a href="%s" target="_blank">Link</a>', value) } ) ), details = function(index) { row <- chapters[index, ] htmltools::div( style = "margin: 16px 24px;", # Top/bottom 16px, left/right 24px htmltools::tags$b("Author info: "), row$Authors, htmltools::br(), htmltools::br(), htmltools::tags$b("Keywords: "), row$Keywords, htmltools::br(), htmltools::br(), div( style = "text-align: justify;", htmltools::tags$b("Abstract: "), row$Abstract ) ) }, compact = TRUE, striped = TRUE, defaultPageSize = 15 ) ``` As research on insect farming has rapidly expanded—driven by advances in genetics, processing, and sustainability—the lack of standardized data analysis and experimental protocols has become a significant barrier to progress and comparability across studies. The BugBook project directly addresses this gap by consolidating both classical and modern data analysis methods, ranging from traditional statistics to advanced machine learning, and by offering practical recommendations for experimental design, microbial and toxicological assessments, and sustainability evaluations. By promoting harmonized methods and rigorous experimental standards, the BugBook project aims to facilitate data interchange, improve transparency, and ensure the replicability of findings in insect research. This initiative is expected to accelerate innovation and support the sustainable development of mass-reared insects as a viable solution for food and feed, ultimately contributing to global food security and environmental sustainability. <br> # Network of collaboration ```{r network, echo=F, message=F, warning=F, out.width="100%"} library(dplyr) library(igraph) library(visNetwork) edges <- authors %>% filter(Chapter != 5) %>% dplyr::group_by(Chapter) %>% summarise(Authors = list(unique(Author)), .groups = "drop") %>% pull(Authors) %>% lapply(function(x) if(length(x) >= 2) t(combn(x, 2)) else NULL) %>% Filter(Negate(is.null), .) %>% do.call(rbind, .) %>% as.data.frame() %>% setNames(c("from", "to")) # Create graph g <- graph_from_data_frame(edges, directed = FALSE) # Create nodes/edges for visNetwork nodes <- data.frame( id = V(g)$name, label = V(g)$name, # Show labels by default font.size = 20, # Larger text color = "#2C5F5D" # Node color ) edges_vis <- as_data_frame(g, what="edges") # Create interactive plot with stabilization visNetwork(nodes, edges_vis) %>% visOptions( highlightNearest=list(enabled = TRUE, degree=1), nodesIdSelection=FALSE ) %>% visPhysics( # Stabilization settings stabilization=list( enabled=TRUE, iterations=100 # More iterations=more stable ), solver="barnesHut", # Better for larger networks barnesHut=list( gravitationalConstant=-5000, # Adjust for node spacing springLength=150 ) ) %>% visLayout(randomSeed = 123) # Consistent initial layout ``` <figcaption> <b>Figure 1. Network showing patterns of collaboration.</b> Scroll to zoom in and out. Click and pull a node to spread out the network. </figcaption> <br> # Geographical distribution ```{r author map, echo=F, message=F, warning=F, out.width="100%"} authors %>% group_by(Author, Institution, City, Country, Lat, Long) %>% summarise( Chapters=paste(sort(unique(Chapter)), collapse=", "), .groups = "drop") %>% leaflet() %>% addProviderTiles(providers$CartoDB.Positron) %>% #addTiles() %>% # Adds the default OpenStreetMap map tiles addCircleMarkers( ~Long, ~Lat, popup = ~paste( "<b>Author: </b>", Author, # author "<br><b>Institute: </b>", Institution, # institution "<br><b>Chapter(s): </b>", Chapters # chapters ), clusterOptions = markerClusterOptions( spiderfyOnMaxZoom = TRUE, # Enable spiderfy showCoverageOnHover = FALSE, zoomToBoundsOnClick = TRUE), radius = 10, # Point size color = "#2C5F5D", # Vibrant orange for visibility fillOpacity = 0.9 ) ``` <figcaption> <b>Figure 2. Interactive map showing the geographical distribution of the people that contributed to the BugBook.</b> <figcaption> <br> </body>